on: 
  push:
    branches:
    - main

name: Build Jekyll Site

jobs:
  build_docs:
    name: Build Jekyll site (latest)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build the site in the jekyll/builder container
      run: |
        docker run --rm \
        --volume="${{ github.workspace }}:/srv/jekyll" \
        jekyll/builder:latest /bin/bash -c "gem install bundler && chmod -R 777 /srv/jekyll && bundle install && bundle exec jekyll build -d build && bundle exec rake search:init"

    - name: Deploy site
      with:
        build-dir: build
      uses:  NickSchimek/deploy_jamstack_action@main